version: '3.8'

services:
  logeion-mcp:
    build: .
    container_name: logeion-mcp-server
    volumes:
      # Mount the database file if it exists locally
      - ./dvlg-wheel-mini.sqlite:/app/dvlg-wheel-mini.sqlite:ro
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; conn = sqlite3.connect('dvlg-wheel-mini.sqlite'); conn.close(); print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # For development/testing, you can uncomment the following lines:
    # ports:
    #   - "8000:8000"
    # stdin_open: true
    # tty: true
